server:
  port: 8082

spring:
  application:
    name: cryonex-account-service

  datasource:
    url: jdbc:mysql://localhost:3306/cryonex_account_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: your_mysql_username
    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        open-in-view: false

logging:
  level:
    root: INFO
    com.cryonex: DEBUG
    org.hibernate.SQL: DEBUG